name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.0.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
            $FLUTTER_HOME/.pub-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/android/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-build

      - name: Configure JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 11
      - run: |
          java -version

      - name: Configure Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1
      - run: |
          dart --disable-analytics
          dart --version

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.2
          channel: stable
      - run: |
          flutter config --no-analytics
          flutter doctor -v
          flutter --version

      - name: Run Analyzer
        run: |
          flutter analyze

  android:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.0.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
            $FLUTTER_HOME/.pub-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/android/*.gradle*', '**/android/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Configure JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 11

      - name: Configure Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.2
          channel: stable

      - name: Build Android
        run: |
          flutter build apk --release --dart-define RELEASE=true --obfuscate --split-debug-info build/app/outputs/symbols-apk/ --target-platform android-arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.0.0
        if: always()
        with:
          name: flutter-app-playground-android-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/app/outputs/apk/release
            build/app/outputs/bundle/release
            build/app/outputs/symbols-apk
            build/app/outputs/symbols-appbundle
          if-no-files-found: warn

  ios:
    runs-on: macos-latest
    needs:
      - build

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.0.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
            $FLUTTER_HOME/.pub-cache
          key: ${{ runner.os }}-pods-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods

      - name: Configure JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 11

      - name: Configure Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.2
          channel: stable

      - name: Build iOS
        run: |
          flutter build ios --release --dart-define RELEASE=true --obfuscate --split-debug-info build/ios/outputs/symbols --no-codesign

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.0.0
        if: always()
        with:
          name: flutter-app-playground-ios-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/ios/Release-iphoneos
            build/ios/symbols
          if-no-files-found: warn

  web:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.0.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
            $FLUTTER_HOME/.pub-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/android/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-web

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11

      - name: Configure Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.2
          channel: stable

      - name: Build Website
        run: |
          flutter build web --release --dart-define RELEASE=true --base-href /flutter-gradle-app-playground/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.0.0
        if: always()
        with:
          name: flutter-app-playground-web-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/web
          if-no-files-found: warn

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - android
      - ios
      - web

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.0.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Configure JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 11

      - name: Configure Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.2
          channel: stable

      - name: Build Website
        run: |
          flutter build web --release --dart-define RELEASE=true --base-href /flutter-gradle-app-playground/

      - name: Publish Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: "Github Actions"
          user_email: "action@github.com"
