name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.4.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2.1.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
            $FLUTTER_HOME/.pub-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/android/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11
      - run: |
          java -version

      - name: Configure Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1
      - run: |
          dart --version

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.2
          channel: stable
      - run: |
          flutter --version
          flutter config --no-analytics
          flutter doctor

      - name: Build Android
        run: flutter build apk --release --obfuscate --split-debug-info build/app/outputs/symbols-apk/ --target-platform android-arm64 --suppress-analytics

      - name: Build iOS
        run: flutter build ios --release --obfuscate --split-debug-info build/ios/outputs/symbols --no-codesign --suppress-analytics

      - name: Build Website
        run: flutter build web --release --base-href /flutter-gradle-app-template/ --suppress-analytics

      - name: Run Analyzer
        run: flutter analyze --suppress-analytics

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: android-gif-example-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/app/outputs/apk/release
            build/app/outputs/bundle/release
            build/app/outputs/symbols-apk
            build/app/outputs/symbols-appbundle
            build/app/reports
            build/ios/Release-iphoneos
            build/ios/symbols
            build/web
          if-no-files-found: warn

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.4.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11

      - name: Configure Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.2
          channel: stable

      - name: Build Website
        run: flutter build web --release --base-href /flutter-gradle-app-template/ --suppress-analytics

      - name: Publish Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: "Github Actions"
          user_email: "action@github.com"
